on:
  push:
    branches:
      - dev
name: Dev branch
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo -n Sleeping for 5 minutes...
          sleep 5m
          echo awake
  
